services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    ports:
      - "8000:8000"
    volumes:
       - .:/app  # Dev only
    environment:
      - DEBUG=True # Dev
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
  celery:
    build: .
    container_name: celery_worker
    command: celery -A django_task_manager worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - web
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"