services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    ports:
      - 7000
    volumes:
       - .:/app  # Dev only
       - /proc:/host_proc:ro
       - /var/log:/host_logs:ro
       - /sys/class/net:/host_net:ro
    environment:
      - HOST_PROC=/host_proc
      - HOST_LOGS=/host_logs
      - HOST_NET=/host_net
      - DEBUG=True # Dev
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
  celery:
    build: .
    container_name: celery_worker
    command: celery -A django_task_manager worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - web
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
      - 8000:8000  # Mapping the original port to Nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles/:/app/media
    depends_on:
      - web
    restart: always